import {StyleSheet} from 'react-native';

export const quesStyle = StyleSheet.create({
  parent: {flex: 1, marginHorizontal: '5%', marginTop: '5%'},
  icon: {alignSelf: 'flex-end', margin: '5%'},
  progressBar: {
    height: 7,
    flexDirection: 'row',
    width: '100%',
    backgroundColor: '#DBDEFF',
    borderWidth: 1,
    borderColor: 'transparent',
  },
  progress: {backgroundColor: '#FF7878', borderRadius: 10},
  title: {
    color: '#4953BE',
    fontSize: 31,
    fontWeight: '500',
    textAlign: 'center',
    marginTop: '5%',
    fontFamily: 'Quicksand-Bold',
  },
  loader: {flex: 1, justifyContent: 'center', alignContent: 'center'},
  subtitle: {
    color: '#4953BE',
    fontSize: 14,
    textAlign: 'center',
    letterSpacing: 5,
  },
  trueBtn: {
    width: '80%',
    borderRadius: 14,
    backgroundColor: '#4953BE',
    height: 64,
    color: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: '2%',
    alignSelf: 'center',
  },
  falseBtn: {
    width: '80%',
    borderRadius: 14,
    backgroundColor: '#fff',
    borderColor: '#4953BE',
    borderWidth: 2,
    height: 64,
    color: 'white',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: '2%',
    alignSelf: 'center',
  },
  question: {
    color: '#4953BE',
    fontSize: 25,
    textAlign: 'left',
    marginTop: '7%',
    fontFamily: 'Quicksand-SemiBold',
    fontWeight: '500',
  },
  btnTextTrue: {
    color: '#fff',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'Quicksand-Bold',
  },
  btnTextFalse: {
    color: '#4953BE',
    fontSize: 15,
    fontWeight: '700',
    fontFamily: 'Quicksand-Bold',
  },
});
